# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [11]:
import numpy as np
import time

s1=time.time()
print(np.zeros((2, 3)))
s2=time.time()


s3=time.time()
print(np.empty((2, 3)))
s4=time.time()
print (s2-s1, s4-s3)
#兩個都是生成初始化一個固定大小的陣列，empty 的內容是亂數取非常近似0得數值，此陣列不會賦與特定的元素值，所以生成比較快

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
0.0010001659393310547 0.0009999275207519531


In [13]:
import numpy as np
import time

s3=time.time()
print(np.empty((2, 3)))
s4=time.time()

s1=time.time()
print(np.zeros((2, 3)))
s2=time.time()

print (s2-s1, s4-s3)
#兩個都是生成初始化一個固定大小的陣列，empty 的內容是亂數取非常近似0得數值，此陣列不會賦與特定的元素值，所以生成比較快

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
0.002000093460083008 0.003000497817993164


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [2]:
# 記得先 Import 正確的套件

import numpy as np

In [16]:

a = np.random.rand(2, 3)
print(a)
print(np.around(a))

[[0.43190593 0.42697803 0.71829559]
 [0.49192537 0.35833619 0.88382814]]
[[0. 0. 1.]
 [0. 0. 1.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [29]:
m = 20
n = 40


[[0.43190593 0.42697803 0.71829559]
 [0.49192537 0.35833619 0.88382814]]


False