# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:
#都可以達到相同結果
#1. a這個ndarray物件中使用的 sum()"這個方法"
#2. 用numpy這個module 中的 sum()函式去計算 a這個物件
#3. python 本來內件的sum()函式

'\nYour Code\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [9]:
# 記得先 Import 正確的套件

import numpy as np
A =np.random.random((5,5))
print(A)

# Z-score normalization (Standardization)

Z = (A- np.mean(A)) / np.std(A)
print(Z)
# (Min-max normalization)

[[0.39433175 0.47887876 0.15006555 0.72890555 0.82008311]
 [0.60626563 0.88552871 0.11455331 0.41860095 0.25014691]
 [0.3286732  0.78748094 0.52329093 0.51887625 0.7315908 ]
 [0.18096999 0.8405868  0.15468211 0.58126059 0.84035213]
 [0.31166108 0.37928171 0.75313429 0.68203998 0.65998271]]
[[-0.54196579 -0.19088877 -1.5562683   0.84733428  1.22594428]
 [ 0.33807846  1.49770369 -1.70373102 -0.4411892  -1.14068573]
 [-0.81460945  1.0905655  -0.00646959 -0.02480131  0.85848461]
 [-1.42793923  1.31108475 -1.5370983   0.23424634  1.31011032]
 [-0.88525138 -0.6044603   0.94794285  0.65272746  0.56113583]]


In [12]:
def zscore(x, axis=None):
    xmean = x.mean(axis = axis)
    xstd = np.std(x, axis = axis)
    zscore = (x-xmean) / xstd
    return zscore

print(zscore(A))


def min_max(x, axis=None):
    xmin_max =  (x- x.min())/ (x.max()-x.min())
    return xmin_max
print(min_max(A))
                 

[[-0.54196579 -0.19088877 -1.5562683   0.84733428  1.22594428]
 [ 0.33807846  1.49770369 -1.70373102 -0.4411892  -1.14068573]
 [-0.81460945  1.0905655  -0.00646959 -0.02480131  0.85848461]
 [-1.42793923  1.31108475 -1.5370983   0.23424634  1.31011032]
 [-0.88525138 -0.6044603   0.94794285  0.65272746  0.56113583]]
[[0.36288893 0.47255134 0.04606145 0.79685064 0.91511324]
 [0.63777952 1.         0.         0.39436751 0.1758728 ]
 [0.27772597 0.87282633 0.5301565  0.52443041 0.80033356]
 [0.08614631 0.94170772 0.05204939 0.60534652 0.94140334]
 [0.25566026 0.34336815 0.82827673 0.73606326 0.70745371]]


In [8]:
A = np.random.random((5, 5))

'''
Your Code
'''

'\nYour Code\n'

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [ ]:
'''
Your Code
'''

[ 0.29347583  0.59303277 -1.          0.38043546  0.63265939  0.32472618
  0.11340241  0.68136955  0.89905432  0.74769935]
