# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [1]:
# 記得先 Import 正確的套件
import numpy as np

In [46]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [49]:
Z

array([[[5, 7, 4, ..., 8, 5, 4],
        [2, 0, 9, ..., 7, 2, 4],
        [3, 1, 4, ..., 9, 9, 6],
        ...,
        [7, 2, 7, ..., 2, 9, 7],
        [9, 9, 1, ..., 3, 5, 0],
        [5, 3, 7, ..., 7, 2, 0]],

       [[3, 2, 5, ..., 4, 1, 9],
        [6, 8, 9, ..., 4, 0, 4],
        [0, 7, 0, ..., 0, 5, 3],
        ...,
        [7, 4, 0, ..., 3, 4, 7],
        [1, 2, 0, ..., 0, 0, 1],
        [1, 5, 4, ..., 5, 3, 8]],

       [[9, 3, 1, ..., 5, 3, 2],
        [1, 6, 1, ..., 0, 7, 9],
        [4, 4, 6, ..., 1, 9, 0],
        ...,
        [7, 4, 0, ..., 5, 3, 9],
        [8, 7, 8, ..., 5, 2, 3],
        [0, 1, 1, ..., 5, 2, 9]],

       ...,

       [[8, 4, 8, ..., 5, 9, 2],
        [8, 4, 0, ..., 6, 1, 7],
        [0, 2, 3, ..., 1, 5, 4],
        ...,
        [7, 4, 2, ..., 6, 4, 1],
        [7, 5, 4, ..., 8, 9, 4],
        [9, 5, 1, ..., 9, 5, 5]],

       [[0, 1, 5, ..., 4, 2, 0],
        [5, 5, 5, ..., 4, 8, 2],
        [4, 7, 1, ..., 4, 4, 9],
        ...,
        [0, 2, 3, ..., 

In [48]:
%timeit -n 10 a = 2
z_list =[]
for i in np.nditer(Z):
    z_list.append(i+1)
    
np.array(z_list).reshape(100,100,100)

33.8 ns ± 13.8 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[ 6,  8,  5, ...,  9,  6,  5],
        [ 3,  1, 10, ...,  8,  3,  5],
        [ 4,  2,  5, ..., 10, 10,  7],
        ...,
        [ 8,  3,  8, ...,  3, 10,  8],
        [10, 10,  2, ...,  4,  6,  1],
        [ 6,  4,  8, ...,  8,  3,  1]],

       [[ 4,  3,  6, ...,  5,  2, 10],
        [ 7,  9, 10, ...,  5,  1,  5],
        [ 1,  8,  1, ...,  1,  6,  4],
        ...,
        [ 8,  5,  1, ...,  4,  5,  8],
        [ 2,  3,  1, ...,  1,  1,  2],
        [ 2,  6,  5, ...,  6,  4,  9]],

       [[10,  4,  2, ...,  6,  4,  3],
        [ 2,  7,  2, ...,  1,  8, 10],
        [ 5,  5,  7, ...,  2, 10,  1],
        ...,
        [ 8,  5,  1, ...,  6,  4, 10],
        [ 9,  8,  9, ...,  6,  3,  4],
        [ 1,  2,  2, ...,  6,  3, 10]],

       ...,

       [[ 9,  5,  9, ...,  6, 10,  3],
        [ 9,  5,  1, ...,  7,  2,  8],
        [ 1,  3,  4, ...,  2,  6,  5],
        ...,
        [ 8,  5,  3, ...,  7,  5,  2],
        [ 8,  6,  5, ...,  9, 10,  5],
        [10,  6,  2, ..., 10,  6

In [44]:
%timeit -n 10 a = 2
Z +=1

33.8 ns ± 13.8 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
%timeit -n 10 a = 2

'''
Your Code
'''

### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [98]:

Z = np.random.randint(0,10,50)
print(Z)


[1 3 9 6 1 5 8 7 3 8 0 6 6 4 0 0 3 6 8 7 7 0 2 5 7 6 7 5 1 1 1 0 5 3 8 9 6
 2 0 7 9 7 8 5 8 5 7 4 6 4]


In [99]:

counter_list=[]

for i in range(10):
    counter = 0
    for j in Z:
        if j==i:
            counter+=1
    counter_list.append(counter)
    
print(counter_list.index (max(counter_list)))

7


In [101]:
index_list=[]
for i in Z.tolist():
    if i == counter_list.index (max(counter_list)):
        index_list.append(Z.tolist().index(i))
        
print(index_list)


[7, 7, 7, 7, 7, 7, 7, 7]


In [105]:
# 答案
ans = np.bincount(Z).argmax()
print(ans)

7


In [107]:
np.where(Z==ans)[0]

array([ 7, 19, 20, 24, 26, 39, 41, 46], dtype=int64)

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [68]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[9, 8, 2, 2, 8, 1]
[9, 8, 2, 2, 8, 1]
[[3, 0, 6, 6], [9, 0, 0, 8], [1, 8, 1, 3]]
[array([3, 0, 6, 6]), array([9, 0, 0, 8]), array([1, 8, 1, 3])]
[[[3, 2], [1, 9], [1, 2]], [[0, 1], [8, 2], [8, 1]]]
[array([[3, 2],
       [1, 9],
       [1, 2]]), array([[0, 1],
       [8, 2],
       [8, 1]])]


In [89]:
def to_list(n):
    if type(n) != np.ndarray:
        return n
    
    a_list=[]
    
    for row in n:
        a_list.append(to_list(row))
    return list(a_list)

to_list(b)





[[3, 0, 6, 6], [9, 0, 0, 8], [1, 8, 1, 3]]