# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [7]:
import numpy as np
a = np.array([[4,8,6],[9,2,1]])
print(a, type(a))
print(a.ndim, a.shape)


[[4 8 6]
 [9 2 1]] <class 'numpy.ndarray'>
2 (2, 3)


In [8]:
#第一種只會轉換ndarray的最外層(最外軸axis)
print('list(a): ', list(a))

#第二種可以完全轉換ndarray中的所有元素
print('tolist():', a.tolist())

list(a):  [array([4, 8, 6]), array([9, 2, 1])]
tolist(): [[4, 8, 6], [9, 2, 1]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [30]:
# 記得先 Import 正確的套件
import numpy as np
a = np.random.randint(10, size=6)
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
print(a, a.ndim, a.shape, a.size,  a.dtype, a.itemsize, len(a), type(a) ,sep='\n')
print('-'*40)
print(b, b.ndim, b.shape, b.size,  b.dtype, b.itemsize, len(b), type(b) ,sep='\n')
print('-'*40)
print(c, c.ndim, c.shape, c.size,  c.dtype, c.itemsize, len(c), type(c) ,sep='\n')
# ndim: ndarray軸的數量
# shape: ndarray的形狀
# size: ndarray中總元素的數量
# dtype: ndarray中，每個元素的資料型別
# itemsize: 以byte為單位，顯示每個元素的記憶體使用量 ex. a的dtype是int32 ，則itemsize = 4 (32 bits/8 = 4 bytes)
# length : ndarray 的最外層(軸)中有多少元素 。  /ndarray shape屬性tuple中最左邊的數字
# type: 查詢資料型態

[4 2 8 6 3 7]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>
----------------------------------------
[[1 7 4 3]
 [7 6 7 4]
 [4 6 5 4]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>
----------------------------------------
[[[4 4]
  [8 1]
  [3 1]]

 [[5 1]
  [6 5]
  [0 7]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [31]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[5, 9, 0, 8, 7, 8]
[5, 9, 0, 8, 7, 8]


In [32]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[1, 7, 4, 7], [6, 4, 8, 6], [2, 1, 9, 8]]
[array([1, 7, 4, 7]), array([6, 4, 8, 6]), array([2, 1, 9, 8])]


In [33]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[8, 3], [8, 4], [9, 7]], [[3, 1], [5, 3], [1, 7]]]
[array([[8, 3],
       [8, 4],
       [9, 7]]), array([[3, 1],
       [5, 3],
       [1, 7]])]


In [ ]:
# 沒想出來
def tolist(iterable):
    '''
    Your Code
    '''
    for i in len(iterable):
        i = list(i)
    return i

print(tolist(a))
print(tolist(b))
print(tolist(c))

[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]


[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]


In [43]:
print(a)
def tolist(itera):
    for i in len(itera):
        c = list(itera)
    return c

print(tolist(a))
#print(tolist(b))
#print(tolist(c))

[5 9 0 8 7 8]


TypeError: 'int' object is not iterable

In [53]:
b

[array([1, 7, 4, 7]), array([6, 4, 8, 6]), array([2, 1, 9, 8])]

In [61]:
ans=[]
for i in b:
    i= list(i)
    ans.append(i)
print(b)
print(ans)

[array([1, 7, 4, 7]), array([6, 4, 8, 6]), array([2, 1, 9, 8])]
[[1, 7, 4, 7], [6, 4, 8, 6], [2, 1, 9, 8]]


In [71]:
ans=[]
for i in c.reshape(-1):
    
    ans.append(i)
print(c)
print(ans)

TypeError: 'numpy.int32' object is not iterable

In [63]:
c.shape

(2, 3, 2)

In [69]:
print(c)
c.reshape(-1)

[[[8 3]
  [8 4]
  [9 7]]

 [[3 1]
  [5 3]
  [1 7]]]


array([8, 3, 8, 4, 9, 7, 3, 1, 5, 3, 1, 7])

In [84]:
print(c)
# 把陣列展開
cc = c.reshape(-1)
print(cc, type(cc))
# 一次轉換
cc = list(cc)
print(cc, type(cc))
#灰復原本型狀
print(c.shape)
ans = cc.reshape((2,3,2))
print(ans)

[[[8 3]
  [8 4]
  [9 7]]

 [[3 1]
  [5 3]
  [1 7]]]
[8 3 8 4 9 7 3 1 5 3 1 7] <class 'numpy.ndarray'>
[8, 3, 8, 4, 9, 7, 3, 1, 5, 3, 1, 7] <class 'list'>
(2, 3, 2)


AttributeError: 'list' object has no attribute 'reshape'