In [1]:
import numpy as np

In [2]:
print(np.array({0:123, 1:456})) #不符合期待

{0: 123, 1: 456}


In [4]:
print(np.array(list({0:123, 1:456}.items())))  #先取出items再list化

[[  0 123]
 [  1 456]]


## <font color= red> 問題來了，不做items()會怎樣?

In [5]:

list({0:1234,1: 4567}) # 直接取會只取key

[0, 1]

In [7]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
#固定大小的序列值開始

print(np.arange(10,30,5)) #注意沒有包含'30'因為只到終值只到29
print(np.linspace(0,10,11)) #0~10 用11個數字作均分 所以是10等分
print(np.logspace(0,2,3)) #預設就是log以10為底 所以是10^0 =1 , 10^2=100 中間3個數字作等比
# 第一個引數表示起始點的指數，第二個引數終止點的指數，第三個引數表示數列的個數

[10 15 20 25]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[  1.  10. 100.]


In [19]:
#可以修改底數
np.logspace(1,10,4,base=2) #修改底數為2


array([   2.,   16.,  128., 1024.])